
package br.ufpe.cin.if998;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculadora", targetNamespace = "http://if998.cin.ufpe.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculadora {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dividir", targetNamespace = "http://if998.cin.ufpe.br/", className = "br.ufpe.cin.if998.Dividir")
    @ResponseWrapper(localName = "dividirResponse", targetNamespace = "http://if998.cin.ufpe.br/", className = "br.ufpe.cin.if998.DividirResponse")
    @Action(input = "http://if998.cin.ufpe.br/Calculadora/dividirRequest", output = "http://if998.cin.ufpe.br/Calculadora/dividirResponse")
    public int dividir(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtrair", targetNamespace = "http://if998.cin.ufpe.br/", className = "br.ufpe.cin.if998.Subtrair")
    @ResponseWrapper(localName = "subtrairResponse", targetNamespace = "http://if998.cin.ufpe.br/", className = "br.ufpe.cin.if998.SubtrairResponse")
    @Action(input = "http://if998.cin.ufpe.br/Calculadora/subtrairRequest", output = "http://if998.cin.ufpe.br/Calculadora/subtrairResponse")
    public int subtrair(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adicionar", targetNamespace = "http://if998.cin.ufpe.br/", className = "br.ufpe.cin.if998.Adicionar")
    @ResponseWrapper(localName = "adicionarResponse", targetNamespace = "http://if998.cin.ufpe.br/", className = "br.ufpe.cin.if998.AdicionarResponse")
    @Action(input = "http://if998.cin.ufpe.br/Calculadora/adicionarRequest", output = "http://if998.cin.ufpe.br/Calculadora/adicionarResponse")
    public int adicionar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplicar", targetNamespace = "http://if998.cin.ufpe.br/", className = "br.ufpe.cin.if998.Multiplicar")
    @ResponseWrapper(localName = "multiplicarResponse", targetNamespace = "http://if998.cin.ufpe.br/", className = "br.ufpe.cin.if998.MultiplicarResponse")
    @Action(input = "http://if998.cin.ufpe.br/Calculadora/multiplicarRequest", output = "http://if998.cin.ufpe.br/Calculadora/multiplicarResponse")
    public int multiplicar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
